"""
Redis async connection pool and client singleton.
Uses redis.asyncio with connection pooling for performance.

Typing note (root fix for the "X is not awaitable" checker noise):
redis-py declares its command methods ONCE on a shared mixin with a
sync/async union return, e.g. `hget(...) -> Union[Awaitable[Optional[str]],
Optional[str]]`. The async client inherits that union WITHOUT narrowing it to
the awaitable branch, so every `await redis.hget(...)` makes mypy/pyright
complain that the non-awaitable branch (`str`/`int`/`None`) isn't awaitable.
That is a library-level typing limitation, not a runtime issue.

We close it at the boundary: `RedisLike` / `_AsyncPipeline` Protocols declare
the exact subset of methods this codebase uses as pure-async (coroutine)
returns, and `get_redis_client()` casts the real client to `RedisLike`. The
cast is a no-op at runtime (`typing.cast` returns its argument unchanged), so
behavior is identical; it only narrows the STATIC type so awaits type-check.
Callers that annotate params (e.g. conversation_state.py) import `RedisLike`.
"""
from functools import lru_cache
from typing import Any, Awaitable, Optional, Protocol, cast

import redis.asyncio as aioredis

from app.config.settings import get_settings

settings = get_settings()


class _AsyncPipeline(Protocol):
    """The subset of the async pipeline used here. Methods return `Any` because
    they serve double duty: queued (not awaited, returns the pipeline) AND
    immediate-while-watching / terminal (awaited). `Any` satisfies both uses."""

    def multi(self) -> Any: ...
    def watch(self, *names: str) -> Any: ...
    def execute(self, raise_on_error: bool = ...) -> Any: ...
    def hget(self, name: str, key: str) -> Any: ...
    def hset(self, *args: Any, **kwargs: Any) -> Any: ...
    def hsetex(self, *args: Any, **kwargs: Any) -> Any: ...
    def hsetnx(self, name: str, key: str, value: Any) -> Any: ...
    def expire(self, name: str, time: int, *args: Any, **kwargs: Any) -> Any: ...
    def incr(self, name: str, amount: int = ...) -> Any: ...
    def lpush(self, name: str, *values: Any) -> Any: ...
    def ltrim(self, name: str, start: int, end: int) -> Any: ...
    def llen(self, name: str) -> Any: ...
    def zadd(self, *args: Any, **kwargs: Any) -> Any: ...
    def zcard(self, name: str) -> Any: ...
    def zremrangebyscore(self, name: str, min: Any, max: Any) -> Any: ...
    async def __aenter__(self) -> "_AsyncPipeline": ...
    async def __aexit__(self, *exc: Any) -> None: ...


class RedisLike(Protocol):
    """Async Redis surface used across the app, typed as pure coroutines so
    `await` type-checks. Permissive `*args/**kwargs` on variadic commands avoids
    signature drift; return types are kept precise where callers consume them."""

    def get(self, name: str) -> Awaitable[Optional[str]]: ...
    def set(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def delete(self, *names: str) -> Awaitable[int]: ...
    def unlink(self, *names: str) -> Awaitable[int]: ...
    def exists(self, *names: str) -> Awaitable[int]: ...
    def rename(self, src: str, dst: str) -> Awaitable[Any]: ...
    def hget(self, name: str, key: str) -> Awaitable[Optional[str]]: ...
    def hmget(self, name: str, keys: Any, *args: Any) -> Awaitable[list]: ...
    def hset(self, *args: Any, **kwargs: Any) -> Awaitable[int]: ...
    def mget(self, keys: Any, *args: Any) -> Awaitable[list]: ...
    def llen(self, name: str) -> Awaitable[int]: ...
    def lrange(self, name: str, start: int, end: int) -> Awaitable[list]: ...
    def scan(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def info(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def ping(self) -> Awaitable[Any]: ...
    def aclose(self) -> Awaitable[None]: ...
    def register_script(self, script: Any) -> Any: ...
    def pipeline(self, transaction: bool = ..., shard_hint: Any = ...) -> _AsyncPipeline: ...


_pool: aioredis.ConnectionPool | None = None


def _create_pool() -> aioredis.ConnectionPool:
    return aioredis.ConnectionPool.from_url(
        settings.redis_url,
        max_connections=settings.redis_max_connections,
        decode_responses=True,
        socket_connect_timeout=5,
        socket_timeout=5,
        retry_on_timeout=True,
    )


@lru_cache(maxsize=1)
def get_redis_client() -> RedisLike:
    """Return the singleton Redis client (cached), typed as `RedisLike` so
    `await` calls type-check (see module docstring). The cast is a runtime
    no-op."""
    global _pool
    _pool = _create_pool()
    return cast(RedisLike, aioredis.Redis(connection_pool=_pool))
