"""
RAG pipeline state definition for LangGraph.
All nodes read from and write to this shared typed state.
"""
import operator
from typing import Annotated, List, Optional, TypedDict

from langchain_core.messages import AnyMessage


class RAGState(TypedDict):
    """
    Shared state for the Optimized RAG pipeline.
    """
    messages: Annotated[list[AnyMessage], operator.add]
    query: str
    conversation_id: str
    intent: Optional[str]
    # Multi-axis scoring (Coexist with intent enum). 0-1 each.
    # Drives prompt assembly without changing routing — see _generate_node.
    intent_scores: Optional[dict]
    error: Optional[str]
    # Holds retrieved chunks from rag_node, consumed by generate_node
    retrieved_context: Optional[List[dict]]
    # Standalone query generated by rewrite_node (if applicable)
    rewritten_query: Optional[str]
    # Query actually sent to retrieval; may differ from rewritten_query when
    # safety escalation is detected (the LLM-supplied safety_preserved_query
    # retains context that the rewrite may have stripped).
    retrieval_query: Optional[str]
    # LLM-supplied safety-anchored version of the user message; used for
    # retrieval when needs_safety_escalation >= 0.5. Empty otherwise.
    # Persisted for observability (agent_logs) so we can audit what the KB
    # actually saw.
    safety_preserved_query: Optional[str]
    conversation_summary: Optional[str]  # Sprint 2 — short-term session summary
    user_profile: Optional[dict]         # Sprint 3 — long-term user memory
    user_preferences: Optional[dict]     # Sprint 4 — persistent user preferences from SQL
    # H5 — precomputed dense embedding of the query, threaded from the chat
    # route (which already embedded for cache/LTM lookup) to avoid a second
    # embed in rag_node. `query_embedding_text` records the EXACT string that
    # embedding was computed from; rag_node reuses the vector ONLY when it
    # matches the text it is about to search (the retrieval query may differ
    # from the embedded query after rewrite/safety-anchoring), else it re-embeds.
    query_embedding: Optional[List[float]]
    query_embedding_text: Optional[str]
    # C4 — pool-level retrieval signals written by rag_node and read by
    # _route_after_rag. Max raw dense cosine / raw BM25 over the FULL fetch_k
    # candidate pool (pre top-k slice), so the NOT-FOUND gate isn't fooled by a
    # high-dense chunk that fell below the fused top-k. `dense_retrieval_ok` is
    # False when retrieval degraded to sparse-only (embedding outage, C5).
    pool_max_dense: Optional[float]
    pool_max_sparse: Optional[float]
    dense_retrieval_ok: Optional[bool]
    # Socratic mentoring toggle (set from ChatRequest.mentoring_mode). When True,
    # _pre_processor promotes a diagnostic/reasoning KNOWLEDGE turn to MENTORING,
    # which routes to the Socratic prompt in generate_node (one grounded guiding
    # question first, then confirm + teach). Pure factual lookups stay direct.
    mentoring_mode: Optional[bool]
    # Set by _pre_processor when the user asked "apa aja di <section>" (items
    # WITHIN one Moodle section, e.g. "Business Process" → Validasi UK, Pelayanan,
    # ...). Reuses the TOPIC_LIST intent + no-retrieval path; generate_node injects
    # this section's item list instead of the full section list. None = the user
    # asked for the full topic/section list (default TOPIC_LIST behavior).
    topic_list_section: Optional[str]

