"""
RAG pipeline state definition for LangGraph.
All nodes read from and write to this shared typed state.
"""
import operator
from typing import Annotated, List, Optional, TypedDict

from langchain_core.messages import AnyMessage


class RAGState(TypedDict):
    """
    Shared state for the Optimized RAG pipeline.
    """
    messages: Annotated[list[AnyMessage], operator.add]
    query: str
    conversation_id: str
    intent: Optional[str]
    # Multi-axis scoring (Coexist with intent enum). 0-1 each.
    # Drives prompt assembly without changing routing — see _generate_node.
    intent_scores: Optional[dict]
    error: Optional[str]
    # Holds retrieved chunks from rag_node, consumed by generate_node
    retrieved_context: Optional[List[dict]]
    # Standalone query generated by rewrite_node (if applicable)
    rewritten_query: Optional[str]
    conversation_summary: Optional[str]  # Sprint 2 — short-term session summary
    user_profile: Optional[dict]         # Sprint 3 — long-term user memory
    user_preferences: Optional[dict]     # Sprint 4 — persistent user preferences from SQL

